_target_: savannah.models.dit_cross_attn.DiTCrossAttnPolicy
embed_dim: 128
num_attn_heads: 4
feedforward_dim: 512
num_blocks: 4
state_dim: 2
action_dim: 2
action_horizon: 12
num_cameras: ${len:${task.config.cameras}}
objective:
  _target_: savannah.objectives.FlowMatchingObjective
  inference_steps: 10
vision_encoder:
  _target_: savannah.models.encoders.vision_encoder.VisionEncoder
  embed_dim: ${model.embed_dim}
  backbone:
    _target_: savannah.models.backbones.resnet_backbone.ResNetBackbone
    out_channels: 96
language_encoder: null
