_target_: savannah.models.dit.DiTPolicy
embed_dim: 512
encoder_num_blocks: 6
encoder_num_attn_heads: 8
encoder_feedforward_dim: 2048
encoder_dropout: 0.1
decoder_num_blocks: 6
decoder_num_attn_heads: 8
decoder_feedforward_dim: 2048
decoder_dropout: 0.1
state_dim: 4
action_dim: 4
action_horizon: 20
num_cameras: ${len:${task.config.cameras}}
objective:
  _target_: savannah.objectives.DDIMObjective
  num_train_timesteps: 100
  num_inference_steps: 10
  beta_start: 1e-4
  beta_end: 0.02
  clip_sample: True
vision_encoder:
  _target_: savannah.models.encoders.vision_encoder.VisionEncoder
  embed_dim: ${model.embed_dim}
  backbone:
    _target_: savannah.models.backbones.clip_backbone.CLIPBackbone
    out_channels: 512
    image_size: ${task.config.image_size}
    base_model: openai/clip-vit-base-patch32
    use_eos_only: True
    trainable: True
language_encoder: null
