_target_: savannah.models.dit.DiTPolicy
embed_dim: 64
encoder_num_blocks: 4
encoder_num_attn_heads: 4
encoder_feedforward_dim: 256
encoder_dropout: 0.1
decoder_num_blocks: 4
decoder_num_attn_heads: 4
decoder_feedforward_dim: 256
decoder_dropout: 0.1
state_dim: 2
action_dim: 2
action_horizon: 12
num_cameras: ${len:${task.config.cameras}}
objective:
  _target_: savannah.objectives.DDIMObjective
  num_train_timesteps: 100
  num_inference_steps: 10
  beta_start: 1e-4
  beta_end: 0.02
  clip_sample: True
vision_encoder:
  _target_: savannah.models.encoders.vision_encoder.VisionEncoder
  embed_dim: ${model.embed_dim}
  backbone:
    _target_: savannah.models.backbones.lora_resnet_backbone.LoRAResNetBackbone
    out_channels: 96
language_encoder: null
