_target_: savannah.models.dit_cross_attn.DITCrossAttnPolicy
embed_dim: 768
time_embed_dim: 128
state_embed_dim: 128
decoder_num_blocks: 8
decoder_num_attn_heads: '${eval: "max(4, ${model.embed_dim}//64)"}'
decoder_feedforward_dim: '${eval: "4 * ${model.embed_dim}"}'
decoder_dropout: 0.1
state_dim: 14
num_obs: ${task.config.obs_horizon}
action_dim: 14
action_horizon: 20
num_cameras: ${len:${task.config.cameras}}
use_rope: true
objective:
  _target_: savannah.objectives.FlowMatchingObjective
  inference_steps: 10
vision_encoder:
  _target_: savannah.models.encoders.vision_encoder.VisionEncoder
  embed_dim: ${model.embed_dim}
  num_cameras: ${model.num_cameras}
  num_obs: ${model.num_obs}
  backbone:
    _target_: savannah.models.backbones.dinov3_backbone.DinoV3Backbone
    image_size: ${task.config.image_size}
    base_model: facebook/dinov3-vits16-pretrain-lvd1689m
    use_eos_only: false
    trainable: false
language_encoder: null
