_target_: savannah.models.unet.UNetPolicy
embed_dim: 128
unet_channels: [256, 512, 1024]
num_residual_layers: 2
num_obs: ${task.config.obs_horizon}
state_dim: 2
action_dim: 2
action_horizon: 8
num_cameras: ${len:${task.config.cameras}}
objective:
  _target_: savannah.objectives.DDIMObjective
  num_train_timesteps: 100
  num_inference_steps: 10
  beta_start: 1e-4
  beta_end: 0.02
  clip_sample: True
vision_encoder:
  _target_: savannah.models.encoders.vision_encoder.VisionEncoder
  embed_dim: ${model.embed_dim}
  backbone:
    _target_: savannah.models.backbones.lora_resnet_backbone.LoRAResNetBackbone
    out_channels: 128
    image_size: ${task.config.image_size}
    lora_rank: 20
    lora_alpha: 40
    use_spatial_softmax: true
