_target_: savannah.tasks.maniskill.ManiSkillColorMatchingTask
config:
  _target_: savannah.data.dataset.DataSetConfig
  repo_id: suhrudhsarathy/color-pick-and-place
  fps: 20
  cameras: ["hand_camera", "front_cam", "side_cam"]
  obs_horizon: 1
  action_horizon: ${model.action_horizon}
  image_size: 128
  batch_size: 32
  num_workers: 4
  train_fraction: 0.95
  cache_in_memory: true
  use_language: true
  augmentation: ${augmentation}
