defaults:
  - model: dit_ddim
  - task: metaworld_button_press
  - trainer: default
  - augmentation: default
  - _self_

name: dit_ddim_metaworld_button_press

wandb:
  project: savannah
  run_name: ${name}
  enable_logging: true
  enable_model_checkpoint: false # upload best/best_success/latest checkpoints as W&B artifacts

log_level: INFO # DEBUG | INFO | WARNING | ERROR
