defaults:
  - model: lbm
  - task: abc_put_bottles
  - trainer: default
  - augmentation: default
  - _self_

name: ${hydra:runtime.choices.model}_${hydra:runtime.choices.task}

wandb:
  project: savannah
  run_name: ${name}
  enable_logging: true
  enable_model_checkpoint: false # upload best/best_success/latest checkpoints as W&B artifacts

log_level: INFO # DEBUG | INFO | WARNING | ERROR
