# Template for multi_run.py
# Run: uv run python scripts/multi_run.py configs/experiments.yaml

vram_per_run_gb: 10

experiments:
  # - name: dit_adaln_pusht
  #   overrides:
  #     - model=dit_adaln
  #     - trainer.checkpoint_dir=checkpoints/dit_adaln
  # - name: dit_adaln_flow_matching_pusht
  #   overrides:
  #     - model=dit_adaln_flow_matching
  #     - trainer.checkpoint_dir=checkpoints/dit_adaln_flow_matching

  - name: dit_cross_pusht
    overrides:
      - model=dit_cross_attn
      - trainer.checkpoint_dir=checkpoints/dit_cross_attn
  - name: dit_cross_attn_flow_matching_pusht
    overrides:
      - model=dit_cross_attn_flow_matching
      - trainer.checkpoint_dir=checkpoints/dit_cross_attn_flow_matching

  # - name: unet_pusht_ddim
  #   overrides:
  #     - model=unet
  #     - trainer.checkpoint_dir=checkpoints/unet_pusht_ddim

  # - name: unet_pusht_flow_matching
  #   overrides:
  #     - model=unet_flow_matching
  #     - trainer.checkpoint_dir=checkpoints/unet_pusht_flow_matching
